name: fail Majors
on:
  pull_request:
    branches: [main]
    paths:
      - 'major/**'

  

    
jobs:
  dummy_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Make renovate automerge excuted'
      -  run: exit 1
      - name: Print message if we don't fail
        run: echo Should not get here
